config/routes.rb
Rails.application.routes.draw do
  root "subjects#home"
  get :home, to: "users#home"

  devise_for :users

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'users'
      devise_for :users, only: []

      resources :users, only: [:index, :show] do
        post :add_to_friends
        post :remove_from_friends
        get :favorites
      end

      resources :subjects, only: [:index, :show] do
        post :like, to: "subjects#like"
        delete :unlike, to: "subjects#unlike"
      end

      resources :organizations do
        resources :posts, only: [:index, :show, :create, :update]
      end

      resources :organization, only: [:index, :show, :create] do
        post "send_invite", to: "memberships#send_invite"
        patch "accept_invite/:user_id", to: "memberships#accept_invite"
        delete "cancel_invite", to: "memberships#cancel_invite"
        get "members", to: "memberships#members"
        get "candidates", to: "memberships#candidates"
        patch "change_role/:user_id/:role", to: "memberships#change_role"
      end

      resources :notifications, only: [:create, :index, :destroy] do
        collection do
          patch :mark_as_read
        end
      end

      resources :lessons, except: [:new, :edit] do
        collection do
          get "subjects/:name", to: "lessons#subjects"
        end
      end

      resources :chatrooms, only: [:index, :show, :create] do
        post "add_participant/:user_id", to: "chatrooms#add_participant"
        get :video_token, to: "chatrooms#video_token"
        get :messages, to: "chatrooms#messages"
      end
    end
  end

  resources :notifications, only: [:create, :index, :destroy] do
    collection do
      post :mark_as_read
      post :subscribe
      get :fetch
    end
  end

  resources :organizations do
    collection do
      get :fetch
      get :home
      get :home_fetch
    end

    resources :posts
    post "send_invite", to: "memberships#send_invite", as: "send_invite"
    patch "accept_invite/:user_id", to: "memberships#accept_invite", as: "accept_invite"
    delete "cancel_invite", to: "memberships#cancel_invite", as: "cancel_invite"
    get "members", to: "memberships#members", as: "members"
    patch "change_role/:user_id/:role", to: "memberships#change_role", as: "change_role"
  end

  #devise_for :users
  get "subjects/fetch", to: "subjects#fetch"
  resources :subjects
  resources :users, only: [:show, :index, :edit, :update] do
    collection do
      get :fetch
    end
    post :friend_request
    post :accept_request
    delete :remove_friend

    patch :change_password
    get :favorites
    resources :lessons, only: [:create, :new, :index, :destroy] do
      collection do
        get :subjects
        get :fetch
      end
    end
  end

  resources :lessons, only: [] do
    collection do
      get :check_if_current_user_is_available
      get :subjects
    end

    post :accept_invite
    delete :decline_invite
  end

  post "add_subject/:id", to: "users#add_subject", as: "add_subject"
  delete "remove_subject/:id", to: "users#remove_subject", as: "remove_subject"

  resources :chatrooms, only: [:index, :show] do
    post :end_video_chat
    post "add_participant/:user_id", to: "chatrooms#add_participant", as: "add_participant"
    get :fetch_users
  end
  post "chatrooms/:user_id", to: "chatrooms#create", as: "new_chatroom"

  get "chatrooms/video_token/:chatroom_id", to: "chatrooms#generate_video_token"

  mount ActionCable.server => '/cable'

  scope :admin do
    get "edit_user/:id", to: "admin#edit_user", as: "admin_edit_user"
    patch "update_user/:id", to: "admin#update_user", as: "admin_update_user"
  end

  namespace :admin do
    resources :organizations, only: [:show, :index] do
      collection do
        get :fetch
      end
      patch :confirm
    end
  end

  get "/:organization_name", to: "organizations#show_by_name", as: "organization_page"
end

app/models/subject.rb
class Subject < ApplicationRecord
  include Filterable
  include Searchable
  include PublicActivity::Common

  scope :featured, -> { where(featured: true) }
  scope :order_by, -> (param) { sort_by(param) }

  has_many :interests, dependent: :destroy
  has_many :users, through: :interests
  belongs_to :parent, class_name: "Subject", optional: true
  has_many :children, class_name: "Subject", foreign_key: :parent_id, dependent: :destroy
  has_many :lessons, dependent: :destroy

  validates :name, presence: true
  validates :headline, presence: true
  validates :description, presence: true

  validate :check_if_parent_id_wont_loop

  mount_uploader :thumbnail, ThumbnailUploader
  mount_uploader :banner, BannerUploader

  private

  def self.sort_by param
    order_params = {
      "oldest" => "created_at ASC",
      "newest" => "created_at DESC"
    }
    self.order(order_params[param])
  end

  def is_inherit_from_child?(id)
    self.children.each do |c|
      return true if c.id == id || c.is_inherit_from_child?(id)
    end
    return false
  end

  def check_if_parent_id_wont_loop
    errors.add(:parent_id, "You cannot inherit subject from himself") if id && parent_id == id
    errors.add(:parent_id, "You cannot inherit subject from his child") if parent_id && is_inherit_from_child?(parent_id)
  end
end

app/controllers/api/v1/subjects_controller.rb
class Api::V1::SubjectsController < Api::V1::BaseController
  rescue_from ActiveRecord::RecordNotFound, with: :wrong_subject_id
  before_action :authenticate_user!, only: %i[like unlike]

  def index
    subjects = Subject.filter(filters_params).search(search_params).page(params[:page])
    render json: subjects
  end

  def show
    subject = Subject.find(params[:id])
    render json: subject
  end

  def like
    subject = Subject.find(params[:subject_id])
    interest = current_user.interests.find_by(subject_id: subject.id)
    if interest
      head(:bad_request) && return
    else
      current_user.interests.create(subject_id: subject.id)
      head(:created) && return
    end
  end

  def unlike
    subject = Subject.find(params[:subject_id])
    interest = current_user.interests.find_by(subject_id: subject.id)
    if interest
      interest.destroy
      head(:no_content) && return
    else
      head(:bad_request) && return
    end
  end

  private

  def filters_params
    params[:filters] ? params.require(:filters).permit(:order_by, :featured) : {}
  end

  def search_params
    params[:search] ? params.require(:search).permit(:name) : {}
  end

  def wrong_subject_id
    render json: { errors: [id: 'Wrong subject id provided'] }
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :home, :fetch]
  before_action :authenticate_admin!, except: [:index, :show, :home, :fetch]
  rescue_from ActiveRecord::RecordNotFound, with: :wrong_subject_id

  def index
    @name = params[:name]
  end

  def fetch
    @subjects = Subject.includes(:children, :interests).filter(filters_params)
      .search(search_params).page(params[:page]).per(10)
    render @subjects
  end

  def home
    redirect_to home_url if current_user
    @featured = Subject.where(featured: true)
  end

  def show
  end

  def new
    @subject = Subject.new
  end

  def edit
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to @subject, notice: 'Subject was successfully created.'
    else
      render :new
    end
  end

  def update
    if @subject.update(subject_params)
      redirect_to @subject, notice: 'Subject was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @subject.destroy
    redirect_to subjects_url, notice: 'Subject was successfully destroyed.'
  end

  private

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def filters_params
    params[:filters]? params.require(:filters).permit(:order_by, :featured) : {}
  end

  def search_params
    params[:search]? params.require(:search).permit(:name) : {}
  end

  def subject_params
    params.require(:subject).permit(:name, :headline, :description,
      :featured, :parent_id, :thumbnail, :thumbnail_cache, :remove_thumbnail,
      :banner, :banner_cache, :remove_banner)
  end

  def wrong_subject_id
    flash[:danger] = 'Wrong id provided'
    redirect_to subjects_path
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(subject) do |f| %>
  <%= errors_for(subject) %>

  <%= f.hidden_field :parent_id %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :headline %>
    <%= f.text_field :headline, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 3, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :featured %>
    <%= f.check_box :featured %>
  </div>

  <div class="form-group">
    <label>thumbnail</label>
    <%= image_tag(@subject.thumbnail_url) if @subject.thumbnail? %>
    <%= f.file_field :thumbnail %>
    <%= f.hidden_field :thumbnail_cache %>
  </div>

  <div class="form-group">
    <label>My banner</label>
    <%= image_tag(@subject.banner_url) if @subject.banner? %>
    <%= f.file_field :banner %>
    <%= f.hidden_field :banner_cache %>
  </div>

  <div class="form-group">
    <label>parent subject</label>
    <input id="subject_picker" autocomplete="off" list="subject_options"
      class="form-control" value="<%= subject.parent.name if subject.parent %>" />
    <datalist id="subject_options">
    </datalist>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/subjects/_nested_subjects.html.erb
<%= link_to "", "#colapse-#{id}", class: "glyphicon glyphicon-chevron-down","data-toggle" => "collapse" %>

<div id="<%= "colapse-#{id}" %>" class="collapse">
  <ul class="list-group">
    <%= render subjects, current_user: current_user %>
  </ul>
</div>

app/views/subjects/_subject.html.erb
<li class="subject list-group-item clearfix">
  <%= link_to subject, class: "pull-left" do %>
    <%= image_tag(subject.thumbnail_url, class: "thumbnail img-rounded", size: "64x64") %>
  <% end %>

  <strong> <%= link_to subject.name, subject %></strong>

  <% if current_user %>
    <% if subject.interests.find_by(user: current_user) %>
      <%= link_to '',"#", class: "unlike-button glyphicon glyphicon-star", data: { id: subject.id } %>
    <% else %>
      <%= link_to '',"#", class: "like-button glyphicon glyphicon-star-empty", data: { id: subject.id }  %>
    <% end %>

    <% if current_user.admin? %>
      <%= link_to 'Edit', edit_subject_path(subject) %>
    <% end %>
  <% end %>

  <h4><%= subject.headline %></h4>

  <% if local_assigns[:without_nested].nil? && subject.children.exists? %>
    <%= render partial: "nested_subjects", locals: { subjects: subject.children, id: rand(1..27101997) } %>
  <% end %>
</li>

app/views/subjects/_subject_option.html.erb
<option data-id="<%= subject.id %>" value="<%= subject.name %>"></option>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>


<%= link_to 'Destroy', @subject, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/home.html.erb
<div id="home-page" class="row">
  <h1>Featured subjects</h1>
  <div id="featured-subjects" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% @featured.each do |subject|%>
        <div class="subject item <%= "active" if @featured[0] == subject%>">
          <%= link_to subject do %>
            <%= image_tag(subject.banner_url) if subject.banner? %>
            <div class="subject-name">
              <h2><%= subject.name %></h2>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <a class="left carousel-control" href="#featured-subjects" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#featured-subjects" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<br />

<div class="row">
        <div class="col-md-offset-2 col-md-8">
              <%= form_tag('/subjects', method: :get) do %>
                <div class="input-group col-md-12">
                    <input name="name" class="form-control input-lg" placeholder="Discover subjects" />
                    <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
                </div>
              <% end %>
        </div>
	</div>

app/views/subjects/index.html.erb
<br />

<div class="col-lg-3">
  <% if current_user && current_user.admin? %>
    <%= button_to 'New Subject', new_subject_path, class: "btn btn-primary", method: "get" %>
  <% end %>

  <form id="search-form">
    <label>Name</label>
    <input type="text" class="form-control" id="name" value="<%= @name %>" />

    <div class="checkbox">
      <label><input id="featured" type="checkbox">featured</label>
    </div>
  </form>
</div>

<div class="col-lg-9">
  <div class="form-group">
    <label for="order_by">Sort</label>
    <select class="form-control" id="order_by">
      <option value='newest'>Newest</option>
      <option value='oldest'>Oldest</option>
    </select>
  </div>

  <ul id="subjects-list" class="list-group">
  </ul>

  <div id="list-loader"><i class="fa fa-circle-o-notch fa-spin" ></i></div>
</div>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<div id="subject">
  <div id="banner">
    <%= image_tag(@subject.banner_url, class: "img-rounded img-responsive") if @subject.banner? %>
    <div id="subject-name">
      <h1>
        <%= @subject.name %>
        <% if current_user %>
        <% if @subject.interests.find_by(user: current_user) %>
        <%= link_to '',"#", class: "unlike-button glyphicon glyphicon-star", data: { id: @subject.id } %>
      <% else %>
        <%= link_to '',"#", class: "like-button glyphicon glyphicon-star-empty", data: { id: @subject.id }  %>
        <% end %>
        <% end %>
      </h1>
      <% if @subject.featured %>
      <div class="glyphicon glyphicon-thumbs-up"></div>
      <strong>
        featured</strong>
      <% end %>
    </div>
  </div>

  <h3><%= @subject.headline %></h3>

  <p><%= @subject.description %></p>

  <% if current_user && current_user.admin? %>
  <%= link_to 'Edit', edit_subject_path(@subject) %>
  <% end %>

  <%= link_to 'Back', subjects_path %>

  <h3>
    Interested users
  </h3>

  <% if current_user %>
  <ul id="interested-users-list" class="list-group">
    <%= render @subject.users %>
  </ul>
<% else %>
  <strong>
    <%= @subject.users.count %>
    users are interested in this subject
  </strong>
  <% end %>
</div>