config/routes.rb
Rails.application.routes.draw do
  root "subjects#home"
  get :home, to: "users#home"

  devise_for :users

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'users'
      devise_for :users, only: []

      resources :users, only: [:index, :show] do
        post :add_to_friends
        post :remove_from_friends
        get :favorites
      end

      resources :subjects, only: [:index, :show] do
        post :like, to: "subjects#like"
        delete :unlike, to: "subjects#unlike"
      end

      resources :organizations do
        resources :posts, only: [:index, :show, :create, :update]
      end

      resources :organization, only: [:index, :show, :create] do
        post "send_invite", to: "memberships#send_invite"
        patch "accept_invite/:user_id", to: "memberships#accept_invite"
        delete "cancel_invite", to: "memberships#cancel_invite"
        get "members", to: "memberships#members"
        get "candidates", to: "memberships#candidates"
        patch "change_role/:user_id/:role", to: "memberships#change_role"
      end

      resources :notifications, only: [:create, :index, :destroy] do
        collection do
          patch :mark_as_read
        end
      end

      resources :lessons, except: [:new, :edit] do
        collection do
          get "subjects/:name", to: "lessons#subjects"
        end
      end

      resources :chatrooms, only: [:index, :show, :create] do
        post "add_participant/:user_id", to: "chatrooms#add_participant"
        get :video_token, to: "chatrooms#video_token"
        get :messages, to: "chatrooms#messages"
      end
    end
  end

  resources :notifications, only: [:create, :index, :destroy] do
    collection do
      post :mark_as_read
      post :subscribe
      get :fetch
    end
  end

  resources :organizations do
    collection do
      get :fetch
      get :home
      get :home_fetch
    end

    resources :posts
    post "send_invite", to: "memberships#send_invite", as: "send_invite"
    patch "accept_invite/:user_id", to: "memberships#accept_invite", as: "accept_invite"
    delete "cancel_invite", to: "memberships#cancel_invite", as: "cancel_invite"
    get "members", to: "memberships#members", as: "members"
    patch "change_role/:user_id/:role", to: "memberships#change_role", as: "change_role"
  end

  #devise_for :users
  get "subjects/fetch", to: "subjects#fetch"
  resources :subjects
  resources :users, only: [:show, :index, :edit, :update] do
    collection do
      get :fetch
    end
    post :friend_request
    post :accept_request
    delete :remove_friend

    patch :change_password
    get :favorites
    resources :lessons, only: [:create, :new, :index, :destroy] do
      collection do
        get :subjects
        get :fetch
      end
    end
  end

  resources :lessons, only: [] do
    collection do
      get :check_if_current_user_is_available
      get :subjects
    end

    post :accept_invite
    delete :decline_invite
  end

  post "add_subject/:id", to: "users#add_subject", as: "add_subject"
  delete "remove_subject/:id", to: "users#remove_subject", as: "remove_subject"

  resources :chatrooms, only: [:index, :show] do
    post :end_video_chat
    post "add_participant/:user_id", to: "chatrooms#add_participant", as: "add_participant"
    get :fetch_users
  end
  post "chatrooms/:user_id", to: "chatrooms#create", as: "new_chatroom"

  get "chatrooms/video_token/:chatroom_id", to: "chatrooms#generate_video_token"

  mount ActionCable.server => '/cable'

  scope :admin do
    get "edit_user/:id", to: "admin#edit_user", as: "admin_edit_user"
    patch "update_user/:id", to: "admin#update_user", as: "admin_update_user"
  end

  namespace :admin do
    resources :organizations, only: [:show, :index] do
      collection do
        get :fetch
      end
      patch :confirm
    end
  end

  get "/:organization_name", to: "organizations#show_by_name", as: "organization_page"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  attr_accessor :starts_at_time, :starts_at_date, :ends_at_time, :ends_at_date

  belongs_to :sender, class_name: "User",  foreign_key: 'sender_id'
  belongs_to :receiver, class_name: "User", foreign_key: 'receiver_id'
  belongs_to :subject

  validate :sender_cannot_be_busy_on_lesson_time
  validate :receiver_cannot_be_busy_on_lesson_time
  validate :time_cannot_be_in_the_past
  #validate :sender_should_be_available_on_lesson_time
  validate :receiver_should_be_available_on_lesson_time

  before_validation :serialize_time, on: :create

  after_create :notify_receiver
  after_update :notify_sender

  private

  def notify_receiver
    receiver.notifications.create(
      message: "You have been invited to study together",
      link: Rails.application.routes.url_helpers.user_lessons_path(receiver.id)
    )
  end

  def notify_sender
    sender.notifications.create(
      message: "#{receiver.name} has accepted your invation to study",
      link: Rails.application.routes.url_helpers.user_lessons_path(sender.id)
    )
  end

  def sender_should_be_available_on_lesson_time
    errors.add(:time, "#{sender.name} is not available at that time") unless sender.available?(time)
  end

  def receiver_should_be_available_on_lesson_time
    errors.add(:time, "#{receiver.name} is not available at that time") unless receiver.available?(time)
  end

  def to_availability_week range
    b = range.begin
    e = range.end
    Time.zone.parse("1996-01-01 #{b.to_s(:time)}") + (b.wday - 1).days ..
    Time.zone.parse("1996-01-01 #{e.to_s(:time)}") + (e.wday - 1).days
  end

  def sender_cannot_be_busy_on_lesson_time
    errors.add(:time, "#{sender.name} is busy at that time") if sender.busy?(time)
  end

  def receiver_cannot_be_busy_on_lesson_time
  errors.add(:time, "#{receiver.name} is busy at that time") if receiver.busy?(time)
  end

  def time_cannot_be_in_the_past
    unless time.begin > Time.current || recurring
      errors.add(:time, "You can`t set up lesson on past days")
    end
  end

  def serialize_time
    self.time = Time.zone.parse("#{starts_at_date} #{starts_at_time}")..Time.zone.parse("#{ends_at_date} #{ends_at_time}")
    self.time = to_availability_week(time) if recurring
  end

  def self.time_for current_user, user
    self.select("time, recurring").where("(sender_id = ? OR receiver_id = ? OR sender_id = ? OR receiver_id = ?) AND confirmed_at IS NOT NULL",
      current_user.id ,current_user.id, user.id, user.id)
  end
end

app/controllers/api/v1/lessons_controller.rb
class Api::V1::LessonsController < Api::V1::BaseController
  rescue_from ActiveRecord::RecordNotFound, with: :wrong_id
  before_action :authenticate_user!

  def index
    render json: current_user.lessons.page(params[:page])
  end

  def subjects
    subjects =  Subject.where("name LIKE ?", "%#{params[:name]}%").page(params[:page])
    render json: subjects
  end

  def update
    lesson = Lesson.find(params[:id])
    if lesson.receiver == current_user
      lesson.update_attribute(:confirmed_at, DateTime.now)
      render json: lesson
    else
      render json: { errors: { receiver: "You are not receiver"}}, status: :bad_request
    end
  end

  def destroy
    lesson = Lesson.find(params[:id])
    if lesson.receiver == current_user || lesson.sender == current_user
      lesson.destroy
      head :no_content and return
    else
      head :bad_request and return
    end
  end

  def create
    lesson = Lesson.new(lesson_params)
    if lesson.save
      render json: lesson, status: :created
    else
      render json: { errors: lesson.errors }, status: :unprocessable_entity
    end
  end

  private

  def lesson_params
    params.require(:lesson).permit(:message, :starts_at_time, :ends_at_time, :private,
      :starts_at_date, :ends_at_date, :subject_id, :receiver_id, :recurring).merge({sender_id: current_user.id})
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :wrong_id
  before_action :authenticate_user!

  def index
  end

  def check_if_current_user_is_available
    if current_user.available?(lesson_time)
      render json: { message: "You are available on that time" }
    else
      render json: { message: "You are not available on that time" }, status: :bad_request
    end
  end

  def fetch
    render Lesson.where(sender_id: current_user.id)
  end

  def subjects
    subjects = Subject.where("lower(name) LIKE ?", "%#{params[:search].downcase}%").map { |subject| {label: subject.name, value: subject.id } }
    render json: subjects
  end

  def accept_invite
    lesson = Lesson.find(params[:id]).includes(:receiver)
    if lesson.receiver == current_user
      lesson.update_attribute(:confirmed_at, Time.current)
      redirect_to user_lessons_path(current_user)
    else
      redirect_to user_lessons_path(current_user), notice: "You cannot accept his invite"
    end
  end

  def decline_invite
    lesson = Lesson.find(params[:id])
    if lesson.receiver == current_user || lesson.sender == current_user
      lesson.destroy
      redirect_to user_lessons_path(current_user)
    else
      redirect_to user_lessons_path(current_user), notice: "You cannot decline this lesson"
    end

  end

  def create
    @user = User.find(params[:user_id])
    @subject = Subject.find(params[:lesson][:subject_id]) if params[:lesson][:subject_id]
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      redirect_to @user, notice: "You have invited this user to study with you"
    else
      p params[:lesson][:starts_at_date]
      render :new
    end
  end

  def new
    @user = User.find(params[:user_id])
    @lesson = Lesson.new(sender_id: current_user.id, receiver_id: @user.id)
  end

  private

  def lesson_time
    starts = Time.zone.parse("#{params[:starts_at_date]} #{params[:starts_at_time]}")
    ends = Time.zone.parse("#{params[:ends_at_date]} #{params[:ends_at_time]}")
    starts..ends
  end

  def lesson_params
    params.require(:lesson).permit(:message, :starts_at_time, :ends_at_time, :private,
      :starts_at_date, :ends_at_date, :subject_id, :receiver_id, :sender_id, :recurring)
  end

  def wrong_id
    flash[:danger] = 'Wrong id provided'
    redirect_to user_lessons_url(current_user)
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
  def lesson_time(time)
    return nil unless time
    time.strftime('%H:%M %d %B')
  end

  def time_ranges_json_for array
    array.map do |range|
      "#{range.begin.strftime('%Y-%m-%dT%H:%M:%S')}..#{range.end.strftime('%Y-%m-%dT%H:%M:%S')}"
    end
  end
end

app/views/lessons/_lesson.html.erb
<li class="lesson media list-group-item">
    <% if lesson.receiver.id == current_user.id %>
      <div class="media-left">
        <%= link_to lesson.sender do %>
          <%= image_tag(lesson.sender.avatar_url, class: "media-object avatar") %>
          <div class="status"><div class="<%= lesson.sender.status %>"></div></div>
        <% end %>
      </div>

      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to lesson.sender.name, lesson.sender %>
          <small><%= link_to "@" + lesson.subject.name, lesson.subject %></small>
        </h4>

        <div class="lesson-message"><%= lesson.message %></div>

        <div class="lesson-time">
          Lesson will take place from <%= lesson_time(lesson.time.begin) %> to <%= lesson_time(lesson.time.end) %>
          <%= "| Recurring" if lesson.recurring? %>
          <%= "| Private" if lesson.private? %>
        </div>

        <% unless lesson.confirmed_at %>
          <%= button_to "Accept", accept_lesson_invite_path(lesson.id), class: "btn btn-success" %>
          <%= button_to "Decline", lesson_decline_invite_path(lesson.id), class: "btn btn-danger", method: :delete %>
        <% end %>
      </div>
    <% else %>
      <h4>
        You invited <%= link_to lesson.receiver.name, lesson.receiver %>
        to study <%= link_to lesson.subject.name, lesson.subject %> together
      </h4>

      <p><%= lesson.message %></p>

      <div class="lesson-time">
        Lesson will take place from <%= lesson_time(lesson.time.begin) %> to <%= lesson_time(lesson.time.end) %>
        <%= "| Recurring" if lesson.recurring? %>
        <%= "| Private" if lesson.private? %>
      </div>

      <% unless lesson.confirmed_at %>
        <%= button_to "Cancel", lesson_decline_invite_path(lesson.id), class: "btn btn-danger", method: :delete %>
      <% end %>
    <% end %>
</li>

app/views/lessons/index.html.erb
<h2>Lessons</h2>
<ul id="lessons-list" class="list-group"></ul>

app/views/lessons/new.html.erb
<div id="lessons-time" data-lessons="<%= time_ranges_json_for(Lesson.time_for(current_user, @user)) %>"></div>
<div id="current-user-availability" data-availability="<%= time_ranges_json_for(current_user.availability) %>"></div>
<div id="user-availability" data-availability="<%= time_ranges_json_for(@user.availability) %>"></div>

<%= link_to "Back to #{@user.name} profile", user_path(@lesson.receiver_id) %>

<hr/>

<%= form_for [@user, @lesson], url: user_lessons_path do |f| %>
  <%= errors_for(@lesson) %>

  <%= f.hidden_field :sender_id %>
  <%= f.hidden_field :receiver_id %>

  <div class="form-group">
    <%= f.label :message %>
    <%= f.text_area :message, rows: 4,  class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :subject %>
    <%= f.select :subject_id, @subject? [[@subject.name, @subject.id]] : [] %>
  </div>

  <div class="lesson">
    <div class="form-group">
      <%= f.label :starts_at %>
      <%= f.text_field :starts_at_date, class: "date start", value: params[:lesson]? params[:lesson][:starts_at_date] : nil %>
      <%= f.text_field :starts_at_time, class: "time start", value: params[:lesson]? params[:lesson][:starts_at_time] :nil %>
    </div>
    <div class="form-group">
      <%= f.label :ends_at %>
      <%= f.text_field :ends_at_date, class: "date end", value: params[:lesson]? params[:lesson][:ends_at_date] :nil %>
      <%= f.text_field :ends_at_time, class: "time end", value: params[:lesson]? params[:lesson][:ends_at_time] :nil %>
    </div>
    <div id="check-user-availability-loader"><i class="fa fa-circle-o-notch fa-spin" ></i></div>
    <div class="alert alert-success" id="user-available">You are available on that time</div>
    <div class="alert alert-warning" id="user-unavailable">You are not available on that time</div>
  </div>

  <div class="form-group">
    <%= f.label :recurring %>
    <%= f.check_box :recurring %>
  </div>

  <div class="form-group">
    <%= f.label :private %>
    <%= f.check_box :private %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>