config/routes.rb
Rails.application.routes.draw do
  root "subjects#home"
  get :home, to: "users#home"

  devise_for :users

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'users'
      devise_for :users, only: []

      resources :users, only: [:index, :show] do
        post :add_to_friends
        post :remove_from_friends
        get :favorites
      end

      resources :subjects, only: [:index, :show] do
        post :like, to: "subjects#like"
        delete :unlike, to: "subjects#unlike"
      end

      resources :organizations do
        resources :posts, only: [:index, :show, :create, :update]
      end

      resources :organization, only: [:index, :show, :create] do
        post "send_invite", to: "memberships#send_invite"
        patch "accept_invite/:user_id", to: "memberships#accept_invite"
        delete "cancel_invite", to: "memberships#cancel_invite"
        get "members", to: "memberships#members"
        get "candidates", to: "memberships#candidates"
        patch "change_role/:user_id/:role", to: "memberships#change_role"
      end

      resources :notifications, only: [:create, :index, :destroy] do
        collection do
          patch :mark_as_read
        end
      end

      resources :lessons, except: [:new, :edit] do
        collection do
          get "subjects/:name", to: "lessons#subjects"
        end
      end

      resources :chatrooms, only: [:index, :show, :create] do
        post "add_participant/:user_id", to: "chatrooms#add_participant"
        get :video_token, to: "chatrooms#video_token"
        get :messages, to: "chatrooms#messages"
      end
    end
  end

  resources :notifications, only: [:create, :index, :destroy] do
    collection do
      post :mark_as_read
      post :subscribe
      get :fetch
    end
  end

  resources :organizations do
    collection do
      get :fetch
      get :home
      get :home_fetch
    end

    resources :posts
    post "send_invite", to: "memberships#send_invite", as: "send_invite"
    patch "accept_invite/:user_id", to: "memberships#accept_invite", as: "accept_invite"
    delete "cancel_invite", to: "memberships#cancel_invite", as: "cancel_invite"
    get "members", to: "memberships#members", as: "members"
    patch "change_role/:user_id/:role", to: "memberships#change_role", as: "change_role"
  end

  #devise_for :users
  get "subjects/fetch", to: "subjects#fetch"
  resources :subjects
  resources :users, only: [:show, :index, :edit, :update] do
    collection do
      get :fetch
    end
    post :friend_request
    post :accept_request
    delete :remove_friend

    patch :change_password
    get :favorites
    resources :lessons, only: [:create, :new, :index, :destroy] do
      collection do
        get :subjects
        get :fetch
      end
    end
  end

  resources :lessons, only: [] do
    collection do
      get :check_if_current_user_is_available
      get :subjects
    end

    post :accept_invite
    delete :decline_invite
  end

  post "add_subject/:id", to: "users#add_subject", as: "add_subject"
  delete "remove_subject/:id", to: "users#remove_subject", as: "remove_subject"

  resources :chatrooms, only: [:index, :show] do
    post :end_video_chat
    post "add_participant/:user_id", to: "chatrooms#add_participant", as: "add_participant"
    get :fetch_users
  end
  post "chatrooms/:user_id", to: "chatrooms#create", as: "new_chatroom"

  get "chatrooms/video_token/:chatroom_id", to: "chatrooms#generate_video_token"

  mount ActionCable.server => '/cable'

  scope :admin do
    get "edit_user/:id", to: "admin#edit_user", as: "admin_edit_user"
    patch "update_user/:id", to: "admin#update_user", as: "admin_update_user"
  end

  namespace :admin do
    resources :organizations, only: [:show, :index] do
      collection do
        get :fetch
      end
      patch :confirm
    end
  end

  get "/:organization_name", to: "organizations#show_by_name", as: "organization_page"
end

app/models/organization.rb
class Organization < ApplicationRecord
  include Filterable
  include Searchable
  include PublicActivity::Common

  scope :order_by, -> (param) { sort_by(param) }
  scope :confirmed, -> { where.not(confirmed_at: nil) }
  scope :unconfirmed, -> { where(confirmed_at: nil) }

  belongs_to :founder, class_name: "User"
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :posts, dependent: :destroy
  has_one :chatroom, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :headline, presence: true
  validates :description, presence: true

  mount_uploader :thumbnail, ThumbnailUploader
  mount_uploader :banner, BannerUploader

  after_create :create_organization_chatroom
  after_create :create_founder_membership

  def members
    users.includes(:memberships)
      .where.not(memberships: { confirmed_at: nil })
      .where(memberships: { organization_id: id })
  end

  def candidates
    users.includes(:memberships)
      .where(memberships: { confirmed_at: nil, organization_id: id })
  end

  def role_of user
    membership = memberships.where.not(confirmed_at: nil).find_by(user_id: user.id)
    return membership.role if membership
  end

  def has_admin? user
    role_of(user) == "admin"
  end

  def has_member? user
    return true if role_of(user)
  end

  def has_candidate? user
    memberships.find_by(user_id: user.id, confirmed_at: nil)
  end

  def has_founder? user
    founder_id == user.id
  end

  def params_url
    name.downcase.gsub(/ /, "-")
  end

  private

  def create_organization_chatroom
    create_chatroom
  end

  def create_founder_membership
    founder.memberships.create(organization_id: id, confirmed_at: Time.current, role: "admin")
  end

  def self.sort_by param
    order_params = {
      "oldest" => "created_at ASC",
      "newest" => "created_at DESC"
    }
    self.order(order_params[param])
  end
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < AdminController
  def confirm
    organization = Organization.find(params[:organization_id])
    if organization.update_attributes(confirmed_at: Time.current)
      redirect_to admin_organizations_path
    else
      redirect_to admin_organizations_path
    end
  end

  def show
    @organization = Organization.find(params[:id])
  end

  def index
    @organizations = Organization.includes(:founder)
  end

  def fetch
    organizations = Organization.filter(filters_params).search(search_params)
      .page(params[:page]).per(10)
    render organizations,
      current_user: current_user
  end

  private

  def filters_params
    params[:filters]? params.require(:filters).permit(:order_by, :unconfirmed, :confirmed) : {}
  end

  def search_params
    params[:search]? params.require(:search).permit(:name) : {}
  end
end

app/controllers/api/v1/organizations_controller.rb
class Api::V1::OrganizationsController < Api::V1::BaseController
  rescue_from ActiveRecord::RecordNotFound, with: :wrong_organization_id
  before_action :authenticate_user!, only: [:create]
  before_action :set_organization, only: [:show]
  before_action :authorizate_founder, only: [:show], unless: :organization_is_confirmed?

  def index
    organizations = Organization.confirmed.filter(filters_params).search(search_params)
    render json: organizations
  end

  def show
    render json: @organization, serializer: FullOraganizationSerializer
  end

  def create
    organization = current_user.foundations.build(organization_params)
    if organization.save
      render json: organization, status: :created
    else
      render json: { errors: organization.errors }, status: :unprocessable_entity
    end
  end

  private

  def organization_params
    params.require(:organization).permit(
      :name, :headline, :description, :banner, :thumbnail, :thumbnail_cache,
      :remove_thumbnail, :banner_cache, :remove_banner)
  end

  def filters_params
    params[:filters]? params.require(:filters).permit(:order_by) : {}
  end

  def search_params
    params[:search]? params.require(:search).permit(:name) : {}
  end

  def organization_is_confirmed?
    @organization.confirmed_at
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def wrong_organization_id
    render json: { errors: { id: "Wrong organization id provided" }}, status: :bad_request
  end

  def authorizate_founder
    unless current_user && @organization.founder.id == current_user.id
      render json: { errors: { permissions: 'You have no permissions' }}, status: :unauthorized
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :home, :home_fetch]
  before_action :set_organization, only: [:show]
  before_action :set_organization_by_name, only: [:show_by_name]
  before_action :authorizate_founder, only: [:show, :show_by_name], unless: :organization_is_confirmed_or_current_user_is_admin

  def fetch
    organizations = Organization.confirmed.filter(filters_params).search(search_params)
      .page(params[:page]).per(10)
    render organizations
  end

  def home_fetch
    if params[:filters][:foundations] == "true"
    organizations = current_user.foundations.filter(filters_params).search(search_params)
      .page(params[:page]).per(10)
    elsif params[:filters][:member] == "true"
      organizations = current_user.confirmed_organizations.filter(filters_params).search(search_params)
        .page(params[:page]).per(10)
    else
      organizations = current_user.organizations.filter(filters_params).search(search_params)
        .page(params[:page]).per(10)
    end
    render organizations
  end

  def show
    @posts = @organization.posts
  end

  def show_by_name
    @posts = @organization.posts
    render :show
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = current_user.foundations.build(organization_params)
    if @organization.save
      redirect_to organizations_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def organization_params
    params.require(:organization).permit(
      :name, :headline, :description, :banner, :thumbnail, :thumbnail_cache,
      :remove_thumbnail, :banner_cache, :remove_banner)
  end

  def set_organization_by_name
    name = params[:organization_name].gsub(/-/, " ")
    @organization = Organization.where('lower(name) = ?', name.downcase).first
  end

  def filters_params
    params[:filters]? params.require(:filters).permit(:order_by, :confirmed, :unconfirmed) : {}
  end

  def search_params
    params[:search]? params.require(:search).permit(:name) : {}
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def organization_is_confirmed_or_current_user_is_admin
    @organization.confirmed_at || current_user.admin?
  end

  def authorizate_founder
    unless current_user && @organization.founder.id == current_user.id
      redirect_to organizations_path, notice: "You have no permissions"
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(organization) do |f| %>
  <%= errors_for(organization) %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :headline %>
    <%= f.text_field :headline, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 3, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>thumbnail</label>
    <%= image_tag(organization.thumbnail_url) if organization.thumbnail? %>
    <%= f.file_field :thumbnail %>
    <%= f.hidden_field :thumbnail_cache %>
  </div>

  <div class="form-group">
    <label>My banner</label>
    <%= image_tag(organization.banner_url) if organization.banner? %>
    <%= f.file_field :banner %>
    <%= f.hidden_field :banner_cache %>
  </div>

  <div class="actions">
    <%= f.submit "Send request", class: "btn btn-success" %>
  </div>
<% end %>

app/views/organizations/_organization.html.erb
<li class="organization list-group-item clearfix">
  <%= link_to organization, class: "pull-left" do %>
    <%= image_tag(organization.thumbnail_url, class: "thumbnail img-rounded", size: "64x64") %>
  <% end %>

  <strong> <%= link_to organization.name, organization_page_path(organization.params_url) %></strong>
  <h4><%= organization.headline %></h4>
</li>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/home.html.erb
<br/>

<div class="col-lg-3">
  <form id="search-form">
    <label>Name</label>
    <input type="text" class="form-control" id="name"/>
    <div class="checkbox">
      <label><input id="confirmed" type="checkbox">Confirmed</label>
    </div>
    <div class="checkbox">
      <label><input id="unconfirmed" type="checkbox">Pending approval</label>
    </div>
    <div class="checkbox">
      <label><input id="founder" type="checkbox">Founded by you</label>
    </div>

    <div class="checkbox">
      <label><input id="member" type="checkbox">Where you are member</label>
    </div>
  </form>
</div>

<div class="col-lg-9">
  <div class="form-group">
    <label for="order_by">Sort</label>
    <select class="form-control" id="order_by">
      <option value='newest'>Newest</option>
      <option value='oldest'>Oldest</option>
    </select>
  </div>

  <div id="list-loader"><i class="fa fa-circle-o-notch fa-spin" ></i></div>

  <ul id="current-user-organizations-list" class="list-group"></ul>
</div>

app/views/organizations/index.html.erb
<br/>

<div class="col-lg-3">
  <form id="search-form">
    <label>Name</label>
    <input type="text" class="form-control" id="name"/>
  </form>
</div>

<div class="col-lg-9">
  <div class="form-group">
    <label for="order_by">Sort</label>
    <select class="form-control" id="order_by">
      <option value='newest'>Newest</option>
      <option value='oldest'>Oldest</option>
    </select>
  </div>

  <div id="list-loader"><i class="fa fa-circle-o-notch fa-spin" ></i></div>

  <ul id="organizations-list" class="list-group"></ul>
</div>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path, class: "btn btn-danger" %>

app/views/organizations/show.html.erb
<div id="organization">
  <div id="banner">
    <%= image_tag(@organization.banner_url, class: "img-rounded img-responsive") if @organization.banner? %>
    <div id="organization-name">
      <h1><%= @organization.name %></h1>
    </div>
  </div>

  <h4>Founded by
    <%= link_to @organization.founder.name, @organization.founder %>
    in
    <%= @organization.created_at.strftime('%d %B %Y') %></h4>
  <h5>
    <%= @organization.name %>
    has
    <%= @organization.members.count %>
    members
    <% if current_user && @organization.has_member?(current_user) %>
    <%= link_to "Go to members list", organization_members_path(@organization) %>
    <% end %>
  </h5>

  <h3><%= @organization.headline %></h3>

  <p><%= @organization.description %></p>

  <% if @organization.has_member?(current_user) %>
  <%= link_to 'Go to chatroom', @organization.chatroom, class: "btn btn-primary" %>
  <% end %>

  <% if current_user && !@organization.has_founder?(current_user) %>
  <% if @organization.has_member?(current_user) %>
  <%= link_to 'Leave', organization_cancel_invite_path(@organization), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?"}  %>
  <% elsif  @organization.has_candidate?(current_user)%>
  <%= link_to 'Cancel invite', organization_cancel_invite_path(@organization), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?"}  %>
<% else %>
  <%= link_to 'Become a member', organization_send_invite_path(@organization), method: :post, class: "btn btn-success" %>
  <% end %>
  <% end %>

  <%= link_to 'Back', organizations_path, class: "btn btn-default" %>
  <hr/>
  <% if current_user && @organization.has_admin?(current_user) %>
  <%= link_to "New post", new_organization_post_path(@organization), class: "btn btn-info" %>
  <% end %>
  <h2>Last news</h2>
  <div id="posts-list" class="list-group">
    <%= render @posts, organization: @organization %>
  </div>
</div>